# Generated by Django 5.1.4 on 2024-12-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.URLField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
