# Generated by Django 5.1.4 on 2024-12-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
