# Generated by Django 5.1.4 on 2024-12-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0002_film_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Draft'), ('BL', 'Blocked'), ('GN', 'Gone')], default='AC', max_length=2)),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='data_api_app.author'),
        ),
    ]
