# Generated by Django 5.1.4 on 2024-12-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0003_author_alter_film_comment_alter_film_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('BL', 'Blocked'), ('GN', 'Gone')], default='AC', max_length=2),
        ),
    ]
