# Generated by Django 5.1.4 on 2024-12-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0003_video_date_released_video_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='author_id',
        ),
    ]
