# Generated by Django 5.1.4 on 2024-12-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0005_rename_film_video_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='num_uploads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
