# Generated by Django 5.1.4 on 2024-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0007_author_firstname_author_lastname_author_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.TextField(default='', max_length=30),
        ),
    ]
