# Generated by Django 5.1.4 on 2024-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api_app', '0008_alter_author_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_about',
            field=models.CharField(default='Astronmy Enthusiast', max_length=50),
            preserve_default=False,
        ),
    ]
